//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CSSParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CSSParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
// [System.CLSCompliant(false)]
public interface ICSSParserListener : IParseTreeListener
{
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.inlinestyle"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterInlinestyle([NotNull] CSSParser.InlinestyleContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.inlinestyle"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitInlinestyle([NotNull] CSSParser.InlinestyleContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.stylesheet"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterStylesheet([NotNull] CSSParser.StylesheetContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.stylesheet"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitStylesheet([NotNull] CSSParser.StylesheetContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.statement"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterStatement([NotNull] CSSParser.StatementContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.statement"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitStatement([NotNull] CSSParser.StatementContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.atstatement"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterAtstatement([NotNull] CSSParser.AtstatementContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.atstatement"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitAtstatement([NotNull] CSSParser.AtstatementContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.import_uri"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterImport_uri([NotNull] CSSParser.Import_uriContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.import_uri"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitImport_uri([NotNull] CSSParser.Import_uriContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.page"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterPage([NotNull] CSSParser.PageContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.page"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitPage([NotNull] CSSParser.PageContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.margin_rule"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterMargin_rule([NotNull] CSSParser.Margin_ruleContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.margin_rule"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitMargin_rule([NotNull] CSSParser.Margin_ruleContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.inlineset"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterInlineset([NotNull] CSSParser.InlinesetContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.inlineset"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitInlineset([NotNull] CSSParser.InlinesetContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.media"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterMedia([NotNull] CSSParser.MediaContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.media"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitMedia([NotNull] CSSParser.MediaContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.media_query"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterMedia_query([NotNull] CSSParser.Media_queryContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.media_query"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitMedia_query([NotNull] CSSParser.Media_queryContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.media_term"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterMedia_term([NotNull] CSSParser.Media_termContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.media_term"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitMedia_term([NotNull] CSSParser.Media_termContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.media_expression"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterMedia_expression([NotNull] CSSParser.Media_expressionContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.media_expression"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitMedia_expression([NotNull] CSSParser.Media_expressionContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.media_rule"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterMedia_rule([NotNull] CSSParser.Media_ruleContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.media_rule"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitMedia_rule([NotNull] CSSParser.Media_ruleContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.keyframes_name"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterKeyframes_name([NotNull] CSSParser.Keyframes_nameContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.keyframes_name"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitKeyframes_name([NotNull] CSSParser.Keyframes_nameContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.keyframe_block"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterKeyframe_block([NotNull] CSSParser.Keyframe_blockContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.keyframe_block"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitKeyframe_block([NotNull] CSSParser.Keyframe_blockContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.keyframe_selector"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterKeyframe_selector([NotNull] CSSParser.Keyframe_selectorContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.keyframe_selector"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitKeyframe_selector([NotNull] CSSParser.Keyframe_selectorContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.unknown_atrule"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterUnknown_atrule([NotNull] CSSParser.Unknown_atruleContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.unknown_atrule"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitUnknown_atrule([NotNull] CSSParser.Unknown_atruleContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.unknown_atrule_body"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterUnknown_atrule_body([NotNull] CSSParser.Unknown_atrule_bodyContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.unknown_atrule_body"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitUnknown_atrule_body([NotNull] CSSParser.Unknown_atrule_bodyContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.ruleset"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterRuleset([NotNull] CSSParser.RulesetContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.ruleset"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitRuleset([NotNull] CSSParser.RulesetContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.declarations"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterDeclarations([NotNull] CSSParser.DeclarationsContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.declarations"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitDeclarations([NotNull] CSSParser.DeclarationsContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.declaration"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterDeclaration([NotNull] CSSParser.DeclarationContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.declaration"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitDeclaration([NotNull] CSSParser.DeclarationContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.important"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterImportant([NotNull] CSSParser.ImportantContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.important"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitImportant([NotNull] CSSParser.ImportantContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.property"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterProperty([NotNull] CSSParser.PropertyContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.property"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitProperty([NotNull] CSSParser.PropertyContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.terms"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterTerms([NotNull] CSSParser.TermsContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.terms"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitTerms([NotNull] CSSParser.TermsContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>termValuePart</c>
    /// labeled alternative in <see cref="CSSParser.term"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterTermValuePart([NotNull] CSSParser.TermValuePartContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>termValuePart</c>
    /// labeled alternative in <see cref="CSSParser.term"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitTermValuePart([NotNull] CSSParser.TermValuePartContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>termInvalid</c>
    /// labeled alternative in <see cref="CSSParser.term"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterTermInvalid([NotNull] CSSParser.TermInvalidContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>termInvalid</c>
    /// labeled alternative in <see cref="CSSParser.term"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitTermInvalid([NotNull] CSSParser.TermInvalidContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.funct"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterFunct([NotNull] CSSParser.FunctContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.funct"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitFunct([NotNull] CSSParser.FunctContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.valuepart"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterValuepart([NotNull] CSSParser.ValuepartContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.valuepart"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitValuepart([NotNull] CSSParser.ValuepartContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.funct_args"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterFunct_args([NotNull] CSSParser.Funct_argsContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.funct_args"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitFunct_args([NotNull] CSSParser.Funct_argsContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.funct_argument"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterFunct_argument([NotNull] CSSParser.Funct_argumentContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.funct_argument"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitFunct_argument([NotNull] CSSParser.Funct_argumentContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.combined_selector"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterCombined_selector([NotNull] CSSParser.Combined_selectorContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.combined_selector"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitCombined_selector([NotNull] CSSParser.Combined_selectorContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.combinator"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterCombinator([NotNull] CSSParser.CombinatorContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.combinator"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitCombinator([NotNull] CSSParser.CombinatorContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.selector"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterSelector([NotNull] CSSParser.SelectorContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.selector"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitSelector([NotNull] CSSParser.SelectorContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.selpart"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterSelpart([NotNull] CSSParser.SelpartContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.selpart"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitSelpart([NotNull] CSSParser.SelpartContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.attribute"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterAttribute([NotNull] CSSParser.AttributeContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.attribute"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitAttribute([NotNull] CSSParser.AttributeContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.pseudo"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterPseudo([NotNull] CSSParser.PseudoContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.pseudo"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitPseudo([NotNull] CSSParser.PseudoContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.string"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterString([NotNull] CSSParser.StringContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.string"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitString([NotNull] CSSParser.StringContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.bracketed_idents"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterBracketed_idents([NotNull] CSSParser.Bracketed_identsContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.bracketed_idents"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitBracketed_idents([NotNull] CSSParser.Bracketed_identsContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.ident_list_item"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterIdent_list_item([NotNull] CSSParser.Ident_list_itemContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.ident_list_item"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitIdent_list_item([NotNull] CSSParser.Ident_list_itemContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.any"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterAny([NotNull] CSSParser.AnyContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.any"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitAny([NotNull] CSSParser.AnyContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.nostatement"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterNostatement([NotNull] CSSParser.NostatementContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.nostatement"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitNostatement([NotNull] CSSParser.NostatementContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.noprop"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterNoprop([NotNull] CSSParser.NopropContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.noprop"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitNoprop([NotNull] CSSParser.NopropContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.norule"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterNorule([NotNull] CSSParser.NoruleContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.norule"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitNorule([NotNull] CSSParser.NoruleContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.nomediaquery"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterNomediaquery([NotNull] CSSParser.NomediaqueryContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.nomediaquery"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitNomediaquery([NotNull] CSSParser.NomediaqueryContext context);
}
