//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CSSParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICSSParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
// [System.CLSCompliant(false)]
public partial class CSSParserBaseListener : ICSSParserListener
{
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.inlinestyle"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterInlinestyle([NotNull] CSSParser.InlinestyleContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.inlinestyle"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitInlinestyle([NotNull] CSSParser.InlinestyleContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.stylesheet"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterStylesheet([NotNull] CSSParser.StylesheetContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.stylesheet"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitStylesheet([NotNull] CSSParser.StylesheetContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.statement"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterStatement([NotNull] CSSParser.StatementContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.statement"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitStatement([NotNull] CSSParser.StatementContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.atstatement"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterAtstatement([NotNull] CSSParser.AtstatementContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.atstatement"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitAtstatement([NotNull] CSSParser.AtstatementContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.import_uri"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterImport_uri([NotNull] CSSParser.Import_uriContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.import_uri"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitImport_uri([NotNull] CSSParser.Import_uriContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.page"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterPage([NotNull] CSSParser.PageContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.page"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitPage([NotNull] CSSParser.PageContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.margin_rule"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterMargin_rule([NotNull] CSSParser.Margin_ruleContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.margin_rule"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitMargin_rule([NotNull] CSSParser.Margin_ruleContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.inlineset"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterInlineset([NotNull] CSSParser.InlinesetContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.inlineset"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitInlineset([NotNull] CSSParser.InlinesetContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.media"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterMedia([NotNull] CSSParser.MediaContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.media"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitMedia([NotNull] CSSParser.MediaContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.media_query"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterMedia_query([NotNull] CSSParser.Media_queryContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.media_query"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitMedia_query([NotNull] CSSParser.Media_queryContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.media_term"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterMedia_term([NotNull] CSSParser.Media_termContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.media_term"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitMedia_term([NotNull] CSSParser.Media_termContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.media_expression"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterMedia_expression([NotNull] CSSParser.Media_expressionContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.media_expression"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitMedia_expression([NotNull] CSSParser.Media_expressionContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.media_rule"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterMedia_rule([NotNull] CSSParser.Media_ruleContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.media_rule"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitMedia_rule([NotNull] CSSParser.Media_ruleContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.keyframes_name"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterKeyframes_name([NotNull] CSSParser.Keyframes_nameContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.keyframes_name"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitKeyframes_name([NotNull] CSSParser.Keyframes_nameContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.keyframe_block"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterKeyframe_block([NotNull] CSSParser.Keyframe_blockContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.keyframe_block"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitKeyframe_block([NotNull] CSSParser.Keyframe_blockContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.keyframe_selector"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterKeyframe_selector([NotNull] CSSParser.Keyframe_selectorContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.keyframe_selector"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitKeyframe_selector([NotNull] CSSParser.Keyframe_selectorContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.unknown_atrule"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterUnknown_atrule([NotNull] CSSParser.Unknown_atruleContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.unknown_atrule"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitUnknown_atrule([NotNull] CSSParser.Unknown_atruleContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.unknown_atrule_body"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterUnknown_atrule_body([NotNull] CSSParser.Unknown_atrule_bodyContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.unknown_atrule_body"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitUnknown_atrule_body([NotNull] CSSParser.Unknown_atrule_bodyContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.ruleset"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterRuleset([NotNull] CSSParser.RulesetContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.ruleset"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitRuleset([NotNull] CSSParser.RulesetContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.declarations"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterDeclarations([NotNull] CSSParser.DeclarationsContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.declarations"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitDeclarations([NotNull] CSSParser.DeclarationsContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.declaration"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterDeclaration([NotNull] CSSParser.DeclarationContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.declaration"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitDeclaration([NotNull] CSSParser.DeclarationContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.important"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterImportant([NotNull] CSSParser.ImportantContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.important"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitImportant([NotNull] CSSParser.ImportantContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.property"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterProperty([NotNull] CSSParser.PropertyContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.property"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitProperty([NotNull] CSSParser.PropertyContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.terms"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterTerms([NotNull] CSSParser.TermsContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.terms"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitTerms([NotNull] CSSParser.TermsContext context) { }
    /// <summary>
    /// Enter a parse tree produced by the <c>termValuePart</c>
    /// labeled alternative in <see cref="CSSParser.term"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterTermValuePart([NotNull] CSSParser.TermValuePartContext context) { }
    /// <summary>
    /// Exit a parse tree produced by the <c>termValuePart</c>
    /// labeled alternative in <see cref="CSSParser.term"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitTermValuePart([NotNull] CSSParser.TermValuePartContext context) { }
    /// <summary>
    /// Enter a parse tree produced by the <c>termInvalid</c>
    /// labeled alternative in <see cref="CSSParser.term"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterTermInvalid([NotNull] CSSParser.TermInvalidContext context) { }
    /// <summary>
    /// Exit a parse tree produced by the <c>termInvalid</c>
    /// labeled alternative in <see cref="CSSParser.term"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitTermInvalid([NotNull] CSSParser.TermInvalidContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.funct"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterFunct([NotNull] CSSParser.FunctContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.funct"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitFunct([NotNull] CSSParser.FunctContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.valuepart"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterValuepart([NotNull] CSSParser.ValuepartContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.valuepart"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitValuepart([NotNull] CSSParser.ValuepartContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.funct_args"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterFunct_args([NotNull] CSSParser.Funct_argsContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.funct_args"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitFunct_args([NotNull] CSSParser.Funct_argsContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.funct_argument"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterFunct_argument([NotNull] CSSParser.Funct_argumentContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.funct_argument"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitFunct_argument([NotNull] CSSParser.Funct_argumentContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.combined_selector"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterCombined_selector([NotNull] CSSParser.Combined_selectorContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.combined_selector"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitCombined_selector([NotNull] CSSParser.Combined_selectorContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.combinator"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterCombinator([NotNull] CSSParser.CombinatorContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.combinator"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitCombinator([NotNull] CSSParser.CombinatorContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.selector"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterSelector([NotNull] CSSParser.SelectorContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.selector"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitSelector([NotNull] CSSParser.SelectorContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.selpart"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterSelpart([NotNull] CSSParser.SelpartContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.selpart"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitSelpart([NotNull] CSSParser.SelpartContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.attribute"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterAttribute([NotNull] CSSParser.AttributeContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.attribute"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitAttribute([NotNull] CSSParser.AttributeContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.pseudo"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterPseudo([NotNull] CSSParser.PseudoContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.pseudo"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitPseudo([NotNull] CSSParser.PseudoContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.string"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterString([NotNull] CSSParser.StringContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.string"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitString([NotNull] CSSParser.StringContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.bracketed_idents"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterBracketed_idents([NotNull] CSSParser.Bracketed_identsContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.bracketed_idents"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitBracketed_idents([NotNull] CSSParser.Bracketed_identsContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.ident_list_item"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterIdent_list_item([NotNull] CSSParser.Ident_list_itemContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.ident_list_item"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitIdent_list_item([NotNull] CSSParser.Ident_list_itemContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.any"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterAny([NotNull] CSSParser.AnyContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.any"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitAny([NotNull] CSSParser.AnyContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.nostatement"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterNostatement([NotNull] CSSParser.NostatementContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.nostatement"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitNostatement([NotNull] CSSParser.NostatementContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.noprop"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterNoprop([NotNull] CSSParser.NopropContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.noprop"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitNoprop([NotNull] CSSParser.NopropContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.norule"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterNorule([NotNull] CSSParser.NoruleContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.norule"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitNorule([NotNull] CSSParser.NoruleContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="CSSParser.nomediaquery"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterNomediaquery([NotNull] CSSParser.NomediaqueryContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="CSSParser.nomediaquery"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitNomediaquery([NotNull] CSSParser.NomediaqueryContext context) { }

    /// <inheritdoc/>
    /// <remarks>The default implementation does nothing.</remarks>
    public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
    /// <inheritdoc/>
    /// <remarks>The default implementation does nothing.</remarks>
    public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
    /// <inheritdoc/>
    /// <remarks>The default implementation does nothing.</remarks>
    public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
    /// <inheritdoc/>
    /// <remarks>The default implementation does nothing.</remarks>
    public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
